# Generated by Django 3.0.7 on 2020-06-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserv_date', models.DateField()),
                ('request_date', models.DateField()),
                ('user', models.CharField(max_length=10)),
            ],
        ),
    ]
