# Generated by Django 3.0.7 on 2020-06-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reserv_date',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reserve_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='request_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
