# Generated by Django 3.0.7 on 2020-07-03 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200619_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='enday_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
